# Generated by Django 4.0.4 on 2022-05-24 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sid', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lvl', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('Status', models.BooleanField(default=True)),
                ('depart', models.CharField(choices=[('AI', 'AI'), ('CS', 'CS'), ('IS', 'IS'), ('IT', 'IT'), ('DS', 'DS')], max_length=2)),
                ('email', models.CharField(max_length=256)),
                ('mobileNum', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cid', models.CharField(max_length=16)),
                ('depart', models.CharField(choices=[('AI', 'AI'), ('CS', 'CS'), ('IS', 'IS'), ('IT', 'IT'), ('DS', 'DS')], max_length=2)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
