# Generated by Django 4.0.4 on 2022-05-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='courses',
            name='depart',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='depart',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='lvl',
            field=models.CharField(max_length=1),
        ),
    ]
