# Generated by Django 4.0.4 on 2022-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_courses_grade_alter_courses_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='depart',
            field=models.CharField(max_length=10),
        ),
    ]
